# --- Constants ---
# Color Palette
PRIMARY_BG = '#1E1F22'
SECONDARY_BG = '#2B2D30'
TERTIARY_BG = '#202124'
ACCENT_COLOR = '#00BFFF'
ACCENT_HOVER = '#009ACD'
SUCCESS_COLOR = '#32CD32'
TEXT_PRIMARY = '#F0F0F0'
TEXT_SECONDARY = '#A0A0A0'
ERROR_FG_CUSTOM = '#FF6347'
WARNING_FG_CUSTOM = '#FFD700'

# Typography
FONT_UI_NORMAL = ('Segoe UI', 12)
FONT_UI_BOLD = ('Segoe UI Semibold', 13)
FONT_UI_HEADER = ('Segoe UI Semibold', 14)
FONT_UI_TITLE = ('Segoe UI Bold', 26)
FONT_CONSOLE_CUSTOM = ('Consolas', 12)
